### Get all task
GET http://localhost:3000/tasks

### Get all task with filter
GET http://localhost:3000/tasks?status=IN_PROGRESS

### Create a new task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title" : "new task happy",
  "description" : "sdff sfsdfsdf service and models"
}

### Update the existing task
PATCH http://localhost:3000/tasks/3/status
Content-Type: application/json

{
  "status" : "IN_PROGRESS"
}


### Get task by Id
GET http://localhost:3000/tasks/2


### Delete task by Id
DELETE http://localhost:3000/tasks/1
